### ISSUE TITLE
Transfer the flyer to the 'monero outreach' repository?

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/Monero-flyer#2]
@SamsungGalaxyPlayer This repository contains just a single document. Would be better to transfer the content of this repo to monero-ecosystem/monero-outreach? The flyer would get more attention and this repo won't look dead

**Comment by SamsungGalaxyPlayer** [comment]
I have no strong opinion. I want this to be easily located when searching for "Monero flyer," and I want to be able to easily make and push updates like I can now. Other than that, I don't really care.

**Comment by erciccione** [comment]
Ok, then i guess for now the best option is to keep this repository and its content as it is.

**Comment by erciccione** [comment]
Same as monero-ecosystem/monero-meetup-kit-localization#34. At the present state, this document doesn't get updated often. I don't think it's necessary to have a dedicated repository for it. Would be a problem for you to open a PR on the outreach repo when/if it's time to upload it? so that we can just move it there and maybe have the outreach workgroup take care of it? ping @lh1008

**Comment by lh1008** [comment]
Hey guys, 

Sure this would be great. Spoke with @xmrhaelan and we are glad to receive Monero-flyer and monero-meetup-kit-localization. Let us know what are the next steps to integrate both to the outreach-docs repo and @SamsungGalaxyPlayer anything you need just let us know, we will be ready for anything you need. 

:)

**Comment by SamsungGalaxyPlayer** [comment]
I have no strong opinions on where this repo is located. All I care about is that it's easily seen by those using a search engine.

**Comment by lh1008** [comment]
So it would better to have its own folder. Search engines will look at the first screen of the repo faster than inside the repo.

**Comment by erciccione** [comment]
Ok, we can transfer it then. SEO optimization can be achieved in many way, especially now that we have the website coming, the flyer could eve nhave its dedicated page. Thank you both for the input

**Comment by lh1008** [comment]
With the website it would be much easier, @erciccione is correct. The repo will just be a place where to work and organize translations, updates, etc. :).
